"""Per-issue detail that makes each GitHub issue self-explanatory.

goal     – one sentence: why this issue exists / what it gives the product
inputs   – what must already exist (files in the repo, Snowflake objects from earlier issues)
outputs  – concrete deliverables (files / Snowflake objects) that prove the issue is done
Used by scripts/build_issues_yaml.py. Keep in sync with CLAUDE_CODE_TEAM_PLAN.md §6 (repo layout).
"""

DETAILS: dict[int, dict] = {
    1: dict(goal="Get every public data source into the repo, versioned and checksummed, so Snowflake can be loaded without internet access.",
            inputs=["`CLAUDE_CODE_DATA_PLAN.md`"],
            outputs=["`data/raw/**` (52 alert PDFs, portal JSON, drug-master subset)", "`data/reference/*`", "`data/manifest.csv`", "`docs/DATA_SOURCES.md`"]),
    2: dict(goal="Produce the human-checked answer key that every extraction accuracy number (#13) is measured against.",
            inputs=["`data/gold/nsq_2025-06_central_gold.csv` (57 rows, pre-filled)", "`data/raw/cdsco_alerts/central/2025-06_central_nsq.pdf`"],
            outputs=["`data/gold/nsq_2025-06_central_gold.csv` with every `verified` cell = `yes`/`fixed` and corrections applied in place"]),
    3: dict(goal="Give the product a realistic (but 100% synthetic) hospital whose dispensing records contain real NSQ batches, plus an answer key.",
            inputs=["`data/interim/nsq_baseline_parsed.csv`", "`data/raw/drug_master/drug_master_subset.csv.gz`"],
            outputs=["`data/synthetic/hospital/*.parquet|csv`", "`data/synthetic/ground_truth/exposures_truth.csv`", "`data/synthetic/README.md`"]),
    4: dict(goal="Let any teammate go from clone to a working CoCo CLI + snow CLI session in 15 minutes, with the same conventions.",
            inputs=["Existing `README.md`, `.gitignore`, `.env.example`"],
            outputs=["`.github/pull_request_template.md`", "`.github/ISSUE_TEMPLATE/task.md`", "`docs/coco_log.md` (template)",
                     "`docs/setup_coco_cli.md`", "`snowflake/config.toml.example`", "`.gitignore` covers `config.toml`, `*.p8`, `.streamlit/secrets.toml`"]),
    5: dict(goal="Agree what the 5 screens show before anyone builds them, and write the 4-minute demo story they must support.",
            inputs=["`CLAUDE_CODE_TEAM_PLAN.md` §1, §5 and #34's story"],
            outputs=["`docs/wireframes.md` (one section per screen: purpose, data shown, actions, source table)", "`docs/demo_script.md` (draft)"]),
    6: dict(goal="Stand up the one shared Snowflake account safely: roles, warehouses and a spending cap, with CoCo CLI working for all three of us.",
            inputs=["Hackathon trial link (claim 26–27 Sep UTC)", "#4 setup guide"],
            outputs=["`snowflake/00_account_setup.sql` (warehouses, resource monitor, cross-region)", "`snowflake/01_rbac.sql` (roles, users, grants)",
                     "3 working user logins", "First 3 entries in `docs/coco_log.md`"]),
    7: dict(goal="Create the database skeleton and encrypted stages every later issue writes into.",
            inputs=["`KAVACH_ADMIN` role + `WH_BUILD` from #6"],
            outputs=["`snowflake/02_database_schemas.sql` (`KAVACH` + RAW/CORE/APP/EVAL/GOV + DEV_A/B/C)",
                     "`snowflake/03_stages.sql` (`@RAW.CDSCO_PDFS`, `@RAW.REFERENCE_DOCS`, `@RAW.HOSPITAL`, SSE + directory)"]),
    8: dict(goal="Put the alert PDFs and reference docs inside Snowflake, plus the baseline/gold tables used for evaluation.",
            inputs=["Stages from #7", "`data/raw/cdsco_alerts/**` (52 PDFs)", "`data/reference/*`", "`data/interim/nsq_baseline_parsed.csv`", "`data/gold/*.csv`"],
            outputs=["`scripts/upload_to_stage.sh`", "`snowflake/04_raw_tables.sql` (file formats + `EVAL.BASELINE_PARSE`, `EVAL.GOLD_NSQ`)",
                     "`DIRECTORY(@RAW.CDSCO_PDFS)` = 52 rows"]),
    9: dict(goal="Load the synthetic hospital into Snowflake as clean, documented CORE tables the matcher can join against.",
            inputs=["Stages from #7", "`data/synthetic/hospital/*.parquet` (8 tables)", "`data/synthetic/ground_truth/*.csv`"],
            outputs=["`snowflake/20_hospital_core.sql`", "RAW.HOSPITAL_* tables, CORE.PATIENTS/WARDS/ENCOUNTERS/PRODUCTS/STOCK_BATCHES/PRESCRIPTIONS/DISPENSING/LABS",
                     "`EVAL.EXPOSURES_TRUTH` (never in CORE/APP)", "`tests/sql_checks/hospital_fk.sql` (0 orphans)"]),
    10: dict(goal="Turn every PDF page into stored markdown text once, so nothing downstream ever re-parses (credit saver).",
             inputs=["`@RAW.CDSCO_PDFS` + directory table from #8"],
             outputs=["`snowflake/10_parse_pages.sql`", "`RAW.NSQ_PAGES(source_file, page_index, content_markdown, parsed_at)`"]),
    11: dict(goal="Turn page text into one structured row per alert line using Cortex, page by page.",
             inputs=["`RAW.NSQ_PAGES` from #10", "`EVAL.BASELINE_PARSE` from #8 (row-count comparison)"],
             outputs=["`snowflake/11_extract_rows.sql`", "`RAW.NSQ_ROWS_EXTRACTED`", "AI_COMPLETE vs AI_EXTRACT decision in `docs/architecture.md`"]),
    12: dict(goal="Clean the extracted rows into the one table the whole product relies on: one row per failed batch.",
             inputs=["`RAW.NSQ_ROWS_EXTRACTED` from #11", "Reference logic: `scripts/parse_baseline.py` (norm_batch, split_batches, norm_date, norm_manufacturer)"],
             outputs=["`snowflake/12_normalize_udfs.sql`", "`snowflake/13_nsq_alert.sql`", "`CORE.NSQ_ALERT`", "`tests/sql_checks/normalize_udfs.sql`"]),
    13: dict(goal="Measure honestly how accurate the Cortex extraction is — this is the headline number for judges.",
             inputs=["Verified gold set from #2", "`CORE.NSQ_ALERT` from #12", "`EVAL.BASELINE_PARSE` from #8"],
             outputs=["`snowflake/50_eval.sql` (extraction part)", "`EVAL.EXTRACTION_METRICS`", "`docs/eval_report.md` (extraction section)"]),
    14: dict(goal="Rank each failed batch by how dangerous it is, so staff see critical items first.",
             inputs=["`CORE.NSQ_ALERT` from #12"],
             outputs=["`snowflake/14_severity.sql`", "`failure_category`, `severity`, `severity_rationale` columns on `CORE.NSQ_ALERT`", "Rules table in `docs/architecture.md`", "30-row spot check in `docs/eval_report.md`"]),
    15: dict(goal="Make a newly uploaded month flow through the whole pipeline with no manual SQL — the live demo moment.",
             inputs=["Working SQL from #10, #11, #12, #14"],
             outputs=["`snowflake/15_automation_tasks.sql` (stream + task graph)", "`.cortex/skills/kavach-monthly-run/SKILL.md`"]),
    16: dict(goal="Extend coverage from July 2025 to August 2026 using the portal data (already fetched: 2,555 rows).",
             inputs=["`data/raw/cdsco_portal/portal_nsq.csv`", "UDFs + `CORE.NSQ_ALERT` from #12"],
             outputs=["Portal rows in `CORE.NSQ_ALERT` with `record_origin='portal'`, months 2025-07 … 2026-08"]),
    17: dict(goal="Find every place a failed batch touched the hospital: stock on the shelf and doses given, tiered by confidence.",
             inputs=["`CORE.NSQ_ALERT` from #12", "CORE hospital tables from #9"],
             outputs=["`snowflake/21_matching_dt.sql`", "Dynamic Table `CORE.BATCH_MATCHES(match_tier, match_score, reasons, …)`"]),
    18: dict(goal="Prove the matcher is right using the synthetic answer key (precision/recall per tier, decoys never flagged).",
             inputs=["`CORE.BATCH_MATCHES` from #17", "`EVAL.EXPOSURES_TRUTH` from #9"],
             outputs=["`snowflake/50_eval.sql` (matching part)", "`EVAL.MATCH_METRICS`", "`docs/eval_report.md` (matching section)"]),
    19: dict(goal="Name the exposed patients and flag those whose labs show warning signs for clinician review.",
             inputs=["`CORE.BATCH_MATCHES` from #17", "`CORE.LABS`, `CORE.DISPENSING`", "Severity/category from #14"],
             outputs=["`snowflake/22_exposure_flags.sql`", "`CORE.PATIENT_EXPOSURE`", "`CORE.CLINICAL_FLAGS(flag_reason, …)`"]),
    20: dict(goal="Turn matches and flags into a to-do list for staff, with calm callback scripts in each patient's language.",
             inputs=["`CORE.PATIENT_EXPOSURE`, `CORE.CLINICAL_FLAGS` from #19", "`CORE.BATCH_MATCHES` (stock to quarantine)"],
             outputs=["`snowflake/23_action_items.sql`", "`APP.ACTION_ITEMS` (+ audit columns `updated_by`, `updated_at`)"]),
    21: dict(goal="Show the product is built for real patient data: PII tagged and masked, rows limited by store, judges read-only.",
             inputs=["Roles from #6", "CORE hospital tables from #9"],
             outputs=["`snowflake/40_governance.sql` (tag, masking policies, row access policy, grants)"]),
    22: dict(goal="Let the app and the agent quote the exact alert page or CDSCO guideline paragraph behind every answer.",
             inputs=["`RAW.NSQ_PAGES` from #10", "Reference PDFs on `@RAW.REFERENCE_DOCS` from #8"],
             outputs=["`snowflake/30_cortex_search.sql`", "`CORE.SEARCH_CHUNKS`", "Cortex Search service `KAVACH_SEARCH`"]),
    23: dict(goal="Describe our tables in business terms so Cortex Analyst can answer plain-English questions correctly.",
             inputs=["Tables from #17, #19, #20"],
             outputs=["`snowflake/31_semantic_view.yaml` / `.sql`", "Semantic view `KAVACH_SV` with ≥10 verified queries"]),
    24: dict(goal="Build the 'Ask Kavach' assistant that combines numbers (Analyst), documents (Search) and a patient timeline tool.",
             inputs=["`KAVACH_SV` from #23", "`KAVACH_SEARCH` from #22"],
             outputs=["`snowflake/32_agent.sql` (agent + `GET_PATIENT_TIMELINE` procedure)", "`tests/agent_questions.yaml` (15 Q&A)", "Agent results in `docs/eval_report.md`"]),
    25: dict(goal="Tell the pharmacy head what changed this month in one paragraph, and email them when new matches appear.",
             inputs=["Automation from #15", "`CORE.BATCH_MATCHES` from #17"],
             outputs=["`snowflake/60_alerts_email.sql` (brief view, notification integration, ALERT)", "A received test email (screenshot)"]),
    26: dict(goal="Give a regulator's-eye view: who fails most, which states don't report, how long bad batches circulate.",
             inputs=["`CORE.NSQ_ALERT` from #12 (+ portal rows from #16 if done)"],
             outputs=["Views in `snowflake/13_nsq_alert.sql` or a new `snowflake/26_regulator_views.sql`"]),
    27: dict(goal="Create the app shell every screen plugs into, running both inside Snowflake and on the public mirror. **Tip:** only needs #7, so start it right after 27 Sep with placeholder queries; don't wait for M3.",
             inputs=["Database/schemas from #7", "Wireframes from #5"],
             outputs=["`app/streamlit_app.py`", "`app/pages/1_Alert_Inbox.py` … `5_Regulator_Accuracy.py`", "`app/lib/session.py`, `app/lib/queries.py`", "`app/requirements.txt`"]),
    28: dict(goal="Build the first thing a pharmacist sees each month and the drill-down to one batch, with a link to the source PDF page.",
             inputs=["App shell from #27", "`CORE.BATCH_MATCHES` from #17", "`APP.ACTION_ITEMS` from #20", "Brief view from #25 (optional)"],
             outputs=["`app/pages/1_Alert_Inbox.py`", "`app/pages/2_Batch_Detail.py`"]),
    29: dict(goal="Show one patient's story (doses, labs, flag) and let staff record the callback outcome.",
             inputs=["App shell from #27", "`CORE.PATIENT_EXPOSURE`, `CORE.CLINICAL_FLAGS` from #19", "`APP.ACTION_ITEMS` from #20"],
             outputs=["`app/pages/3_Patient_Card.py`", "Write-back into `APP.ACTION_ITEMS`"]),
    30: dict(goal="Put the Kavach Assistant in the app as a chat with citations.",
             inputs=["App shell from #27", "Agent from #24"],
             outputs=["`app/pages/4_Ask_Kavach.py`", "`app/lib/agent.py`"]),
    31: dict(goal="Show the regulator insights and, honestly, how accurate Kavach is.",
             inputs=["Views from #26", "`EVAL.EXTRACTION_METRICS` (#13)", "`EVAL.MATCH_METRICS` (#18)", "App shell from #27"],
             outputs=["`app/pages/5_Regulator_Accuracy.py`"]),
    32: dict(goal="Give judges a public link that works on a phone, read-only and masked, with no secrets in the repo.",
             inputs=["Screens from #28–#30", "Judge role + masking from #21"],
             outputs=["Public Streamlit Community Cloud URL (in README)", "Service user with key-pair auth", "Judge-login fallback documented"]),
    33: dict(goal="Prove the whole thing rebuilds from the repo with one command (and can be torn down).",
             inputs=["All `snowflake/*.sql` from M1–M3"],
             outputs=["`scripts/deploy.sh` / `make deploy`", "`snowflake/99_teardown.sql`", "Rebuild steps in `README.md`"]),
    34: dict(goal="Rehearse the 4-minute story until it runs cleanly twice with no manual SQL.",
             inputs=["Automation (#15), email alert (#25), screens (#28–#31)"],
             outputs=["Final `docs/demo_script.md` with timings", "Notes from 2 dry runs"]),
    35: dict(goal="Write the mandatory prototype document judges read first.",
             inputs=["`docs/eval_report.md` (#13, #18, #24)", "`docs/architecture.md`", "`docs/coco_log.md`"],
             outputs=["`docs/MVP.md`", "`docs/MVP.pdf`"]),
    36: dict(goal="Record the demo so judges (and the finale) have it even if the trial account is gone.",
             inputs=["Rehearsed script from #34"],
             outputs=["Unlisted video link in `README.md` and `docs/MVP.md`"]),
    37: dict(goal="Show judges CoCo CLI was central to the build, not decorative. **Ongoing:** log sessions as you go from #6 onward; only the wrap-up happens in M4.",
             inputs=["Each person's CoCo sessions (start logging now)", "Automation + skill from #15"],
             outputs=["≥9 entries in `docs/coco_log.md`", "Working `.cortex/skills/kavach-monthly-run/SKILL.md`", "'How we used CoCo CLI' section in `docs/MVP.md`"]),
    38: dict(goal="Don't lose the account, the credits or the app before judging and the finale are over. **Ongoing:** the daily credit check starts the day #6 activates the trial; the backup and finale plan are the M4 part.",
             inputs=["Resource monitor from #6"],
             outputs=["Backup of key tables attached to a GitHub release", "Finale plan section in `README.md`"]),
    39: dict(goal="Submit on time with every link working.",
             inputs=["Public link (#32)", "MVP doc (#35)", "Video (#36)"],
             outputs=["Hack2skill submission confirmation screenshot (attach to this issue)"]),
}

CRITICAL_PATH = {6, 7, 8, 9, 10, 11, 12, 17, 19, 20, 23, 24, 28, 29, 30, 32, 34, 39}
CRITICAL_PATH.add(14)  # #19 consumes severity/category from #14

# Items whose plan task text is a list of *things* rather than *steps*: explicit ordered steps.
STEPS_OVERRIDE: dict[int, str] = {
    14: """- [ ] **1.** Run `AI_CLASSIFY` on `nsq_result` into these categories: sterility / endotoxin · particulate matter · toxic contaminant (DEG/EG) · assay (strength) · dissolution · description / labeling · spurious · other → `failure_category`
- [ ] **2.** Derive `dosage_form` (injection, oral liquid, tablet/capsule, other) from the product name
- [ ] **3.** Apply rules (category × dosage form) → `severity` = critical / high / low. Examples: sterility or particulate in an injectable → **critical**; DEG/EG in an oral liquid → **critical**; description only → **low**
- [ ] **4.** Write a one-line `severity_rationale` per row
- [ ] **5.** Spot-check 30 rows by hand (≥90% agreement) and document the rules table""",
}
CRITICAL_PATH.add(22)  # #24 (agent) cannot start without the search service
CRITICAL_PATH.update({35, 36})  # both feed straight into the submission (#39)
