-- BatchTrace: Database, schemas, warehouse, stages, file format
-- Run as ACCOUNTADMIN on a new Snowflake account.

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND  = 60
  AUTO_RESUME   = TRUE;

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS BATCHTRACE;

CREATE SCHEMA IF NOT EXISTS BATCHTRACE.RAW;
CREATE SCHEMA IF NOT EXISTS BATCHTRACE.CORE;
CREATE SCHEMA IF NOT EXISTS BATCHTRACE.APP;

-- Internal stage for CDSCO alert PDFs (directory table enabled)
CREATE STAGE IF NOT EXISTS BATCHTRACE.RAW.CDSCO_PDFS
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY  = (ENABLE = TRUE);

-- Internal stage for seed CSV data
CREATE STAGE IF NOT EXISTS BATCHTRACE.RAW.SEED_DATA;

-- CSV file format used by all COPY INTO statements
CREATE FILE FORMAT IF NOT EXISTS BATCHTRACE.RAW.CSV_FMT
  TYPE                      = CSV
  SKIP_HEADER               = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL       = TRUE
  ENCODING                  = 'UTF8';
